#!/bin/sh -e

REQUIRES='core'
DESCRIPTION='Install Ansible'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

ansible_branch='stable-2.2'

ansible_tmpdir=$(mktemp -d crouton-ansible.XXXXXX --tmpdir=/tmp)
addtrap "rm -rf --one-file-system '$ansible_tmpdir'"

install git-core
install --minimal --asdeps asciidoc build-essential cdbs debhelper devscripts \
                           dh-python fakeroot lintian lsb-release python \
                           python-setuptools xsltproc
release=$(lsb_release -cs)
cd "$ansible_tmpdir"
git clone --recursive https://github.com/ansible/ansible.git
cd ansible
git checkout "$ansible_branch"
git submodule update
make DEB_DIST="$release" debian
make DEB_DIST="$release" local_deb
install_pkg deb-build/${release}/ansible_*.deb

if [ ! -f /root/run-ansible ]; then
  cat <<'_EOF_' > /root/run-ansible
#!/bin/sh
set -exu

repo_uri='https://github.com/jamebus/ansible'
checkout='production'
playbook='base.yml'

ansible-pull -i 'localhost,' -U "$repo_uri" -C "$checkout" "$playbook"
_EOF_
  chmod 0755 /root/run-ansible
fi
